# Copyright (c) 2021 Autodesk, Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Autodesk, Inc.

import os
import sgtk

HookBaseClass = sgtk.get_hook_baseclass()


class BreakdownSceneOperations(HookBaseClass):
    """
    Breakdown operations for Adode Premiere.
    """

    def scan_scene(self):
        """
        The scan scene method is executed once at startup and its purpose is
        to analyze the current scene and return a list of references that are
        to be potentially operated on.

        The return data structure is a list of dictionaries. Each scene reference
        that is returned should be represented by a dictionary with three keys:

        - "node_name": The name of the 'node' that is to be operated on. Most DCCs have
          a concept of a node, path or some other way to address a particular
          object in the scene.
        - "node_type": The object type that this is. This is later passed to the
          update method so that it knows how to handle the object.
        - "path": Path on disk to the referenced object.
        - "extra_data": Optional key to pass some extra data to the update method
          in case we'd like to access them when updating the nodes.

        Toolkit will scan the list of items, see if any of the objects matches
        a published file and try to determine if there is a more recent version
        available. Any such versions are then displayed in the UI as out of date.
        """
        self.logger.info("Scanning...")
        refs = []
        try:
            engine = self.parent.engine
            current_project = engine.current_project
            if not current_project:
                self.logger.info("No current project, skipping...")
                return refs
            for clip in current_project.clips:
                refs.append(
                    {
                        "node_name": clip.name,
                        "node_type": "clip",
                        "path": clip.media_path,
                        "extra_data": {
                            # Seems safer to not keep a reference to the clip
                            # but retrieve it later?
                            "node_id": clip.node_id,
                        }
                    }
                )
            self.logger.info("Refs found: %s" % refs)
            return refs
        except Exception as e:
            self.logger.exception(e)
            raise

    def update(self, item):
        """
        Perform replacements given a number of scene items passed from the app.

        Once a selection has been performed in the main UI and the user clicks
        the update button, this method is called.

        :param item: Dictionary on the same form as was generated by the scan_scene hook above.
                     The sg_data key holds the Published File that the node should be
                     updated *to* rather than the current Published File.
        :returns: The path the item was set to, ``False`` if no update was done.
        """

        self.logger.info("Updating %s" % item)
        node_name = item["node_name"]
        node_type = item["node_type"]
        sg_data = item["sg_data"]
        if not sg_data or not sg_data.get("path", {}).get("local_path", None):
            return False
        path = sg_data["path"]["local_path"]
        node_id = item["extra_data"]["node_id"]
        engine = self.parent.engine
        current_project = engine.current_project
        # For now just update the path in place.
        clip = current_project.get_clip_by_id(node_id)
        if not clip:
            self.logger.warning("Unable to retrieve a clip with id %s" % node_id)
            return False
        clip.media_path = path
        self.logger.info("%s updated with %s" % (clip, path))
        return path
